### ISSUE TITLE
TypeError: null is not an object Evaluating (blob.prototype)

### ISSUE THREAD

**Issue by usmanarif12** [ApiRTC/apirtc-react-native-demo#8]
I recently cloned this project and run it after npm install.  the app runs successfully but when i tried to add this feature in my another project and runs it .. it gives me an error 
**TypeError: null is not an object Evaluating (Blob.prototype)**
I tried following steps

-  tried to link `react-native-webrtc` using npm link , but error persists
-  Tried to link manually , but error persists
-   Also i added all necessary dependencies i.e `react-native-device-info` , `react-native-event-listeners`,
- `react-native-permissions` , `socket.io-client` and `react-native-webrtc`, but still giving me error
- Do not forget that i do added  `apiRtc-React.min.js` 
![Screenshot_20200712_160208](https://user-images.githubusercontent.com/40420829/87245226-2a5d9480-c45d-11ea-8246-580e0a8bd453.jpg)
.  

But don't know why giving me this error. Please help me to solve this issue..

Environment Details:
Windows 10
React native version 0.62
Android real device with android 9

**Comment by SavinienBarbotaud** [comment]
New version of react-native-apirtc and tutorial has been released.
Check https://www.npmjs.com/package/@apirtc/react-native-apirtc
